# Generated by Django 5.0.1 on 2024-01-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=5, verbose_name='سایز')),
                ('url_title', models.SlugField(max_length=30, unique=True, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='url_title',
            field=models.SlugField(max_length=300, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.SlugField(max_length=300, verbose_name='عنوان در url'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='product_size', to='product_module.productsize', verbose_name='سایز'),
        ),
    ]
