# Generated by Django 5.0.1 on 2024-01-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productsize_alter_productbrand_url_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='url_title',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='نام در url'),
        ),
    ]
