# Generated by Django 4.1.2 on 2024-01-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_productbrand_url_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ'),
        ),
    ]
