# Generated by Django 4.1.2 on 2024-01-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_productcolor_remove_product_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='رنگ'),
        ),
    ]
